services:
  weaviate:
    image: semitechnologies/weaviate:1.29.0 
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50051:50051" 
    environment:
      QUERY_DEFAULTS_LIMIT: 2500
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "./weaviate_data"
      DEFAULT_VECTORIZER_MODULE: "text2vec-openai"
      ENABLE_MODULES: "text2vec-openai"
      CLUSTER_HOSTNAME: "node1"
      OPENAI_APIKEY: "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"  
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data: