# services:
#   weaviate:
#     image: semitechnologies/weaviate:1.29.0 
#     restart: unless-stopped
#     ports:
#       - "8080:8080"
#       - "50051:50051" 
#     environment:
#       QUERY_DEFAULTS_LIMIT: 2500
#       AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
#       PERSISTENCE_DATA_PATH: "./weaviate_data"
#       DEFAULT_VECTORIZER_MODULE: "text2vec-openai"
#       ENABLE_MODULES: "text2vec-openai"
#       CLUSTER_HOSTNAME: "node1"
#       OPENAI_APIKEY: "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"  
#     volumes:
#       - weaviate_data:/var/lib/weaviate

# volumes:
#   weaviate_data:





# Weaviate + FastAPI Docker Compose

# version: "3.8"

# services:
#   weaviate:
#     image: semitechnologies/weaviate:1.29.0 
#     restart: unless-stopped
#     ports:
#       - "8080:8080"
#       - "50051:50051" 
#     environment:
#       QUERY_DEFAULTS_LIMIT: 2500
#       AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
#       PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
#       DEFAULT_VECTORIZER_MODULE: "text2vec-openai"
#       ENABLE_MODULES: "text2vec-openai"
#       CLUSTER_HOSTNAME: "node1"
#       OPENAI_APIKEY: "${OPENAI_API_KEY}"
#     volumes:
#       - weaviate_data:/var/lib/weaviate

#   fastapi:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "${FASTAPI_PORT:-8000}:8000"
#     environment:
#       - WEAVIATE_HOST=http://weaviate:8080
#       - OPENAI_API_KEY=${OPENAI_API_KEY}
#     depends_on:
#       - weaviate

# volumes:
#   weaviate_data:



# Weaviate + FastAPI Docker Compose
# version: "3.8"

# services:
#   weaviate:
#     image: semitechnologies/weaviate:1.29.0 
#     container_name: weaviate
#     restart: unless-stopped
#     ports:
#           - "${WEAVIATE_PORT}:8080"     # REST API
#           - "50051:50051"             # gRPC API
#     environment:
#       QUERY_DEFAULTS_LIMIT: 2500
#       AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
#       PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
#       DEFAULT_VECTORIZER_MODULE: "text2vec-openai"
#       ENABLE_MODULES: "text2vec-openai"
#       CLUSTER_HOSTNAME: "node1"
#       OPENAI_APIKEY: "${OPENAI_API_KEY}"
#     healthcheck:
#       test: ["CMD-SHELL", "wget --spider -q http://localhost:8080/v1/meta || exit 1"]
#       interval: 5s
#       timeout: 5s
#       retries: 10
#     volumes:
#       - weaviate_data:/var/lib/weaviate
#     networks:
#       - app-network

#   fastapi:
#     env_file: .env
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: fastapi
#     ports:
#       - "${FASTAPI_PORT:-8000}:8000"
#     environment:
#       - WEAVIATE_HOST=http://weaviate:8080   # 🔥 This enables Docker-internal access
#       - OPENAI_API_KEY=${OPENAI_API_KEY}
#     depends_on:
#       weaviate:
#         condition: service_healthy
#     networks:
#       - app-network

# volumes:
#   weaviate_data:

# networks:
#   app-network:
#       driver: bridge


# Compose only FastAPI
version: "3.8"

services:
  fastapi:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "${FASTAPI_PORT:-8000}:8000"
    environment:
      - WEAVIATE_HOST=${WEAVIATE_HOST}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
